### ISSUE TITLE
Support for HTC Wildfire S (MarvelC)

### ISSUE THREAD

**Issue by JmzTaylor** [koush/ROMManagerManifest#369]
Repo is here.  https://github.com/jmztaylor/android_device_htc_marvelc

**Comment by insink71** [comment]
Good tree... I was looking for the graphics.c file referenced on the BoardConfig.mk as we had some early pink & green recoveries.  Was working toward rebuilding marvel's device tree myself ;) But this appears a lot cleaner than their's.  Perhaps it doesn't need it, but those early pink & green recoveries still haunt my subconscious.  I know this... at a minimum you'll need gralloc copybits... see #358 for reference. https://github.com/koush/ROMManagerManifest/issues/358
HCDRJacob's will work changing everything from marvel to marvelc... I was just cleaning up the ril stuff that got thrown in since our devices are cdma.  I suppose, not sure, but I suppose that he threw them in for the test keys function ::shrug::  Anyway, if I can help, I usually do.

Rob

**Comment by JmzTaylor** [comment]
Yeah I had it in there and it got deleted sometime.  But now this tree is updated and fixed that.

**Comment by insink71** [comment]
sweet.. can't wait to peep it out.. Thanks again for your nice work.
