### ISSUE TITLE
Themes For Rom Manager from Michael Lyford

### ISSUE THREAD

**Issue by RoLa** [koush/ROMManagerManifest#91]
Hey Koush, I was wondering if you could please add my info to your Master Manifest? I tried forking, editing, but it was an epic fail. Thanks for everything. 
http://pastebin.com/xhTrsAVg

**Comment by bcrook** [comment]
Is this waiting to be added?

**Comment by RoLa** [comment]
Yes. It has not been added yet. Thanks

**Comment by bcrook** [comment]
It says this link: http://jbthemes.com/RoLa/ROMManagerManifest/Rola.js is invalid

**Comment by RoLa** [comment]
My manifest isn't there yet. I have it made. Does it need to be there for you to get it to work?

**Comment by bcrook** [comment]
I would prefer it...otherwise people will see the manifest, click on your ROM link and see an error. 

If you can do a pull request instead, that is much easier...but if you dont want to mess with git, I won't blame you. If you want to learn, add me to gtalk or email me and I can help you out. 
brian.w.crook@gmail.com
